---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: benz-walter-crls
spec:
  {{- with .Values.ingress }}
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end }}
  rules:
  - host: {{ .host | quote }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: benz-walter-crls
            port:
              name: http
    {{- end }}
