{{- if .Values.serviceAccount.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: benz-walter-crls
rules:
- apiGroups: [""]
  resources: ["services", "serviceaccounts", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benz-walter-crls

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: benz-walter-crls
subjects:
- kind: ServiceAccount
  name: benz-walter-crls
  apiGroup: ""
roleRef:
  kind: Role
  name: benz-walter-crls
  apiGroup: ""

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: benz-walter-crls
  annotations:
    kubernetes.io/service-account.name: benz-walter-crls

{{- end }}
