ingress:
  # The host under which the application should be reachable.
  host: ""

  # The ingress class to use.
  # Will use the default one defined in the cluster of left empty.
  ingressClassName: ""

general:
  # Custom secrets to pull images from external repositories.
  # See: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  image:
    # Image to use.
    name: "ghcr.io/benz-walter/crls/crls"

    # Image tag to use, defaults to Chart.AppVersion
    tag: ""

    # Defines the pull policy of the image.
    # Can be 'Never', 'IfNotPresent' and 'Always'
    pullPolicy: Always


serviceAccount:
  # Creates a service account which will be able to maintain the deployment within the namespace.
  # A secret will be automatically created which contains the CA and token for that account.
  # You can get the CA and token via:
  #   kubectl get -n <namespace> secret/benz-walter-crls -o jsonpath="{.data.ca\.crt}" | base64 --decode
  #   kubectl get -n <namespace> secret/benz-walter-crls -o jsonpath="{.data.token}" | base64 --decode
  enabled: false
